import { BaseFields, CONFIGURABLE_MODEL_FIELDS } from "@/model";
import { PrefixedConfigurables } from "@/model/types";
import { WorkflowState, WorkflowUpdate } from "@/schemas";
import { RunnableConfig } from "@langchain/core/runnables";
import { execSync } from "child_process";

export type PublisherConfigFields = PrefixedConfigurables<"publisher", BaseFields>

type PublisherConfig = RunnableConfig & {
    configurable?: PublisherConfigFields
}

export const publisherNode = async (state: WorkflowState, config: PublisherConfig): Promise<WorkflowUpdate> => {
    const { project } = state;
    if (!project.sandbox?.rootPath) {
        return {
            messages: [{ content: "No sandbox path found. Writer must run first.", role: "assistant" }]
        }
    }

    const repoName = project.name;
    const sandboxPath = project.sandbox.rootPath;

    try {
        // Change directory to sandbox and initialize git
        process.chdir(sandboxPath);

        execSync("git init", { stdio: "inherit" });
        execSync("git add .", { stdio: "inherit" });
        execSync(`git commit -m "Initial commit: project generated by workflow"`, { stdio: "inherit" });

        const visibility = project.isPrivate ? "--private" : "--public";
        // Use gh repo create with --source=. to link current dir and --push to push to remote
        execSync(`gh repo create ${repoName} ${visibility} --source=. --push`, { stdio: "inherit" });

        return {
            messages: [{ content: `Project successfully published to GitHub as ${repoName}`, role: "assistant" }],
            project: {
                ...project,
                repoUrl: `https://github.com/${process.env.GITHUB_USERNAME || 'user'}/${repoName}`
            }
        }
    } catch (error: any) {
        console.error("Publisher Error:", error);
        return {
            messages: [{ content: `Error publishing to GitHub: ${error.message}`, role: "assistant" }]
        }
    } finally {
        // Return to a safe directory to avoid locking the sandbox if needed
        process.chdir(process.cwd());
    }
};
